### ISSUE TITLE
Grayscale images. (frontend)

### ISSUE THREAD

**Issue by Tyler929** [Archkitten/python_experts#25]
- Look for Hack in code.
- Change to greyscale dynamically
- If need help go [here](https://github.com/katiehickman/flask_portfolio/blob/main/lists.py) + [here](https://github.com/katiehickman/flask_portfolio/blob/main/main.py) for reference. (Crossover team)

**Comment by Archkitten** [comment]
7b68ad6f761828f98ce4f11d560acd48f3dadee1

**Comment by Archkitten** [comment]
a0bb621ff644493a8323f43ca68553c89b113442
