### ISSUE TITLE
Extend/Switch ASCII  to Unicode

### ISSUE THREAD

**Issue by willcyber** [Archkitten/python_experts#36]
Extend/Switch ASCII  to Unicode.

- [ ] Use representation of U-0000 to U-FFFF for your bits.  The extension of ASCII to Unicode mode allows you to show even more Characters and Character ranges.  Look at Unicode on Wikipedia (Links to an external site.).

**Comment by Archkitten** [comment]
bdc27cd2a08e1f0378208bf280e064f1d555d436

**Comment by Archkitten** [comment]
cb917e31e632998406b69826460694e3d6babfbd
